### PR TITLE
clear output

### PR DESCRIPTION
**Pull request by cleemansen**

### CODE REVIEW

**Review by andreakoelzsch — COMMENTED** [review]
Hi Clemens, the only change here is the addition of the Clear_output. Do I understand it correctly that it is always true on MoveApps, but that the developer can adapt it for his/her purposes in the local runs? Changing the alternative path for artefacts from /tmp/ to "." might not work for Windows users, but I have not tested it (yet). Please wait for review from Anne for this Template

**Comment by cleemansen** [comment]
Hi Andrea. This is a feature request from Anne. I also mentioned the possible glitch between execution during local development and in production on MoveApps. I do not have a complete overview about cleaning the filesystem on MoveApps during each lifecycle phase. But there is a clean up action on MoveApps, too! If this is important I can do an investigation.

As far as I know this cleanup is super helpful during development.

**Comment by andreakoelzsch** [comment]
Thanks Clemens, I guess this is fine, just wanted some feedback how this is handled in MoveApps. All good

**Comment by cleemansen** [comment]
> Changing the alternative path for artefacts from /tmp/ to "." might not work for Windows users.

This is a fallback option. If the env var for artifacts is not set we must fall back to this value (I believe this is a requirement by the R API of `Sys.env`.
I would expect that on Windows the fallback `/tmp` is even more problematic as this directory does not exist on Windows? It is just a default on Linux.
And the `.` as the _current directory_ should hopefully work on Windows, too?!

**Comment by andreakoelzsch** [comment]
The "." works in RStudio Windows now. I had problems with this earlier in the cargo agent unit test files, but this will likely come up again anyway, so never mind for now. Thanks!

**Comment by annescharf** [comment]
Thanks Clemens for adding this. @andreakoelzsch I though even though it might not replicate the exact behavior of moveapps, having a empty output folder for each run is very helpful while developing the app when things change a lot. Hope you agree :)

**Review by annescharf — APPROVED** [review]

**Pull request merged**
